ProyectoWeb/Blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.blog, name="blog"),
    path("categoria/<int:categoria_id>/", views.categoria, name="categoria")
]

ProyectoWeb/Carro/urls.py
from django.urls import path
from . import views


# creamos un especie de namespace
# para que sea mas facil usar las urls de carro
app_name = "carro"

urlpatterns = [
    path("agregar/<int:producto_id>/<pagina>", views.agrega_producto, name="agregar"),
    path("eliminar/<int:producto_id>/", views.elimina_producto, name="eliminar"),
    path("resta/<int:producto_id>/", views.resta_producto, name="restar"),
    path("limpia/", views.limpia_carro, name="limpiar"),
    path("carro/", views.muestra_carro, name="carro"),

]

ProyectoWeb/ProyectoWeb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("Aplicacion1.urls")),
    path("servicios/", include("Servicios.urls")),
    path("blog/", include("Blog.urls")),
    path("contacto/", include("Contacto.urls")),
    path("tienda/", include("Tienda.urls")),
    path("carro/", include("Carro.urls")),
    path("autenticacion/", include("Autenticacion.urls")),
    path("pedidos/", include("Pedidos.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

ProyectoWeb/Tienda/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("", views.tienda, name="tienda"),
]

ProyectoWeb/Carro/models.py
from django.db import models

# Create your models here.

ProyectoWeb/Tienda/models.py
from django.db import models

# Create your models here.

class CategoriaProd(models.Model):
    nombre = models.CharField(max_length=100)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)

    class Meta():
        verbose_name = "Categoria Producto"
        verbose_name_plural =  "Categorias Producto"

    def __str__(self):
        return self.nombre
    

class Producto(models.Model):
    nombre = models.CharField(max_length=200)
    categorias = models.ForeignKey(CategoriaProd, on_delete=models.CASCADE)
    imagen = models.ImageField(upload_to="tienda", null=True, blank=True)
    precio = models.FloatField()
    disponibilidad = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now_add=True)
    
    class Meta():
        verbose_name = "Producto"
        verbose_name_plural =  "Productos"

    def __str__(self):
        return self.nombre

ProyectoWeb/Carro/views.py
from django.shortcuts import render, redirect
from .Carro import *
from Tienda.models import Producto

# Create your views here.
def agrega_producto(request, producto_id, pagina):
    carro = Carro(request)
    producto_a_agregar = Producto.objects.get(id=producto_id)
    carro.agregar(producto_a_agregar)

    # enviar mensaje
    
    if pagina == "tienda":
        return redirect("tienda")
    else:
        return redirect("carro:carro")

def elimina_producto(request, producto_id):
    carro = Carro(request)
    producto_a_eliminar = Producto.objects.get(id=producto_id)
    carro.eliminar(producto_a_eliminar)
    return redirect("carro:carro")

def resta_producto(request, producto_id):
    carro = Carro(request)
    producto_a_restar = Producto.objects.get(id=producto_id)
    carro.restar_producto(producto_a_restar)

    return redirect("carro:carro")


def limpia_carro(request):
    carro = Carro(request)
    carro.limpia_carro()
    return redirect("tienda")


def muestra_carro(request):
    return render(request, "Carro/carro.html")

ProyectoWeb/Tienda/views.py
from django.shortcuts import render
from .models import *
# Create your views here.



def tienda(request):
    productos = Producto.objects.all()
    return render(request, "Tienda/tienda.html", {"productos": productos})

ProyectoWeb/Tienda/templates/Carro/carro.html
{% extends "Aplicacion1/base.html" %}

{% block title %} Carro {% endblock %}

{% block cabecera %}Tu carro de compras{% endblock %}

{% block content %}


<div style="width: 80%; margin: auto;">

    <table class="table table-bordered">
    
        <thead>
            <tr>
                <th colspan="3" class="text-center">
                    Carro
                </th>
            </tr>
        
            <tr>
                <th>Producto</th>
                <th>Cantidad</th>
                <th>Suma</th>
            </tr>
        </thead> <!--fin del table head-->
        
        <tbody>
            {% if request.session.carro.items %}
                {% for key, value in request.session.carro.items %}
                    <tr class="text-center">
                        <td>
                            {{value.nombre}}
                        </td>
                        <td>
                            {{value.cantidad}}
                        </td>
                        <td>
                            <a href="{% url 'carro:agregar' value.id_producto 'carro' %}" class="btn btn-primary">+</a>
                            <a href="{% url 'carro:restar' value.id_producto %}" class="btn btn-primary">-</a>
                            <a href="{% url 'carro:eliminar' value.id_producto %}" class="btn btn-primary">C</a>
                            <p>${{value.precio}}</p>
                        </td>
                        
                    </tr>
                {% endfor %}
                <a href="{% url 'carro:limpiar' %}" class="btn btn-danger me-2 mb-2">Limpiar Carro</a>
        
            {% else %}
                <tr>
                    <th colspan="3">
                        <div class="alert alert-danger text-center">
                            Sin Productos
                        </div>
                    </th>
                </tr>
            {% endif %}
            <tr>
                <th colspan="3" class="text-center">
                    <p>Total: CLP${{importe_total_carro}}</p>
                </th>
            </tr>
        
            {% if request.session.carro.items %}
            <tr>
                <th colspan="3" class="text-center">
                    <a href="{% url 'pedido' %}" class="btn btn-primary">Hacer Pedido</a>
                </th>
            </tr>
            {% endif %}
        </tbody> <!--fin de tbody-->
        
        
        
        </table>

    <a href="{% url 'tienda' %}" class="btn btn-primary">Volver</a>    
</div>

{% endblock %}

ProyectoWeb/Tienda/templates/Carro/widget.html
<head>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined:opsz,wght,FILL,GRAD@48,700,0,200" />
</head>

<a href="{% url 'carro:carro' %}">
<button style="position: fixed; bottom: 20px; right: 20px; padding: 15px 20px; cursor: pointer; border-radius: 50%;">
    <span class="material-symbols-outlined">
        shopping_cart</span>
</button>
</a>